// Generated by gencpp from file point_message/statsMsg.msg
// DO NOT EDIT!


#ifndef POINT_MESSAGE_MESSAGE_STATSMSG_H
#define POINT_MESSAGE_MESSAGE_STATSMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace point_message
{
template <class ContainerAllocator>
struct statsMsg_
{
  typedef statsMsg_<ContainerAllocator> Type;

  statsMsg_()
    : xSD(0)
    , ySD(0)
    , xCent(0)
    , yCent(0)  {
    }
  statsMsg_(const ContainerAllocator& _alloc)
    : xSD(0)
    , ySD(0)
    , xCent(0)
    , yCent(0)  {
    }



   typedef int32_t _xSD_type;
  _xSD_type xSD;

   typedef int32_t _ySD_type;
  _ySD_type ySD;

   typedef int32_t _xCent_type;
  _xCent_type xCent;

   typedef int32_t _yCent_type;
  _yCent_type yCent;




  typedef boost::shared_ptr< ::point_message::statsMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::point_message::statsMsg_<ContainerAllocator> const> ConstPtr;

}; // struct statsMsg_

typedef ::point_message::statsMsg_<std::allocator<void> > statsMsg;

typedef boost::shared_ptr< ::point_message::statsMsg > statsMsgPtr;
typedef boost::shared_ptr< ::point_message::statsMsg const> statsMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::point_message::statsMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::point_message::statsMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace point_message

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'point_message': ['/home/peter/thrust_vis/src/imu_msgs/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::point_message::statsMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::point_message::statsMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point_message::statsMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point_message::statsMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_message::statsMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_message::statsMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::point_message::statsMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0774c5ae2f41c65f0564a155f4857204";
  }

  static const char* value(const ::point_message::statsMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0774c5ae2f41c65fULL;
  static const uint64_t static_value2 = 0x0564a155f4857204ULL;
};

template<class ContainerAllocator>
struct DataType< ::point_message::statsMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "point_message/statsMsg";
  }

  static const char* value(const ::point_message::statsMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::point_message::statsMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 xSD\n\
int32 ySD\n\
int32 xCent\n\
int32 yCent\n\
";
  }

  static const char* value(const ::point_message::statsMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::point_message::statsMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xSD);
      stream.next(m.ySD);
      stream.next(m.xCent);
      stream.next(m.yCent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct statsMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::point_message::statsMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::point_message::statsMsg_<ContainerAllocator>& v)
  {
    s << indent << "xSD: ";
    Printer<int32_t>::stream(s, indent + "  ", v.xSD);
    s << indent << "ySD: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ySD);
    s << indent << "xCent: ";
    Printer<int32_t>::stream(s, indent + "  ", v.xCent);
    s << indent << "yCent: ";
    Printer<int32_t>::stream(s, indent + "  ", v.yCent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POINT_MESSAGE_MESSAGE_STATSMSG_H
